name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: pre-commit/action@v3.0.0
    - run: pip install ".[dev]"
    - run: pytest --color=yes
