name: Release

on:
  workflow_dispatch:
  release:
    types:
    - published

jobs:
  release:
    if: github.repository_owner == 'related-sciences'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/oai_utils
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install release dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Build a source distribution and a wheel
      run: |
        python -m build
        python -m twine check --strict dist/*
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: dist
    - name: Publish package
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
